version: "3"

services:
  zoo1:
    image: zookeeper
    container_name: zoo1
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - "19092:19092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  orders_mgr_api:
    image: "145742810091.dkr.ecr.us-east-1.amazonaws.com/orders-management-api:${TAG1}"
    container_name: orders_mgr_api
    env_file:
      - orders_mgr_api.env
    ports:
      - 1337:1337
    depends_on:
      - kafka1
      - zoo1

  orders_match_engine:
    image: "145742810091.dkr.ecr.us-east-1.amazonaws.com/exchange-orders-match-engine:${TAG2}"
    container_name: orders_match_engine
    ports:
      - 8081:8081
    depends_on:
      - orders_mgr_api

  market:
    image: "145742810091.dkr.ecr.us-east-1.amazonaws.com/exchange-market:${TAG3}"
    container_name: market
    ports:
      - 8080:8080
    depends_on:
      - orders_match_engine
